SUPABASE_URL = "https://ljhzwbbtcmyvtcaecflf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaHp3YmJ0Y215dnRjYWVjZmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NDc3MTQsImV4cCI6MjA5NjEyMzcxNH0.I0HhY8hSYtF8mkgr1wQC0_8PWezWhA9tXQcpawtHpQw"
